require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.nvimtree_config")
require("core.plugin_config.mason_config")
require("core.plugin_config.nvim-comp_config")
